name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - '**'
      - '!README.md'

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  ODOO_ENTERPRISE_TOKEN: ${{ secrets.ODOO_ENTERPRISE_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}
  SKIP_UNIT_TESTS: true
  TARGET_PLATFORMS: amd64
  DOCKER_BUILDKIT: '1'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    concurrency:
      group: docker-${{ matrix.branch }}
      cancel-in-progress: true
    strategy:
      matrix:
        branch: [ "master" ]
      fail-fast: false
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository on branch ${{ matrix.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Extract Docker metadata
        if: github.event_name != 'pull_request'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.branch }},enable=true

      - name: Extract Docker metadata (scraper)
        if: github.event_name != 'pull_request'
        id: meta_scraper
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-scraper
          tags: |
            type=raw,value=${{ matrix.branch }},enable=true

      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.TARGET_PLATFORMS }}
          build-args: |
            ODOO_VERSION=${{ matrix.branch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

      - name: Build and push Scraper Docker image
        if: github.event_name != 'pull_request'
        id: build-and-push-scraper
        uses: docker/build-push-action@v5
        with:
          context: ./scripts/real_estate_scraper
          file: ./scripts/real_estate_scraper/Dockerfile
          platforms: ${{ env.TARGET_PLATFORMS }}
          tags: ${{ steps.meta_scraper.outputs.tags }}
          labels: ${{ steps.meta_scraper.outputs.labels }}
          push: true
